"use client"
import Link from 'next/link'
import {useMemo,useState} from 'react'
import {PositionBadge} from './position-badge'
type Player={id:string;fullName:string;position:string;club:string;age:number;rating:number;minutes:number;marketValue:number;status:string}
export function PlayersBrowser({players}:{players:Player[]}){const[query,setQuery]=useState('');const[position,setPosition]=useState('All');const[club,setClub]=useState('All');const[sort,setSort]=useState('rating');const[view,setView]=useState('table');const positions=['All',...Array.from(new Set(players.map(p=>p.position)))];const clubs=['All',...Array.from(new Set(players.map(p=>p.club)))];const filtered=useMemo(()=>players.filter(p=>p.fullName.toLowerCase().includes(query.toLowerCase())).filter(p=>position==='All'||p.position===position).filter(p=>club==='All'||p.club===club).sort((a,b)=>Number(b[sort as keyof Player])-Number(a[sort as keyof Player])),[players,query,position,club,sort]);return <div><div style={{display:'flex',gap:12,flexWrap:'wrap',margin:'22px 0'}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search by name' style={input}/><select value={position} onChange={e=>setPosition(e.target.value)} style={input}>{positions.map(v=><option key={v}>{v}</option>)}</select><select value={club} onChange={e=>setClub(e.target.value)} style={input}>{clubs.map(v=><option key={v}>{v}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} style={input}><option value='rating'>Rating</option><option value='age'>Age</option><option value='marketValue'>Market Value</option><option value='minutes'>Minutes</option></select><button onClick={()=>setView(view==='table'?'grid':'table')} style={button}>{view==='table'?'Grid':'Table'}</button></div>{view==='table'?<table style={{width:'100%',borderCollapse:'collapse',background:'#18181b',borderRadius:18,overflow:'hidden'}}><thead><tr><th style={th}>Player</th><th style={th}>Pos</th><th style={th}>Club</th><th style={th}>Age</th><th style={th}>Rating</th><th style={th}>Minutes</th><th style={th}>Value</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} style={{borderTop:'1px solid #27272a'}}><td style={td}><Link href={`/players/${p.id}`}>{p.fullName}</Link></td><td style={td}><PositionBadge position={p.position}/></td><td style={td}>{p.club}</td><td style={td}>{p.age}</td><td style={td}>{p.rating}</td><td style={td}>{p.minutes}</td><td style={td}>€{(p.marketValue/1000000).toFixed(1)}M</td></tr>)}</tbody></table>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:16}}>{filtered.map(p=><Link key={p.id} href={`/players/${p.id}`} style={card}><PositionBadge position={p.position}/><h3>{p.fullName}</h3><p style={{color:'#a1a1aa'}}>{p.club} · {p.age} yrs</p><strong>{p.rating}</strong></Link>)}</div>}</div>}
const input={padding:12,borderRadius:12,border:'1px solid #27272a',background:'#18181b',color:'#fff'}
const button={...input,cursor:'pointer'}
const th={padding:14,textAlign:'left',color:'#a1a1aa'} as const
const td={padding:14} as const
const card={background:'#18181b',border:'1px solid #27272a',borderRadius:18,padding:20,display:'block'}
