const risers=[{name:'João Pedro',club:'Brighton',trend:'+12 OBV'},{name:'Rayan Cherki',club:'Lyon',trend:'+9 Creativity'},{name:'Arthur Vermeeren',club:'Atlético',trend:'+8 Progression'}]
const opportunities=[{name:'Sávio',tag:'Undervalued Winger'},{name:'Alan Varela',tag:'Press Resistant DM'},{name:'Facundo Buonanotte',tag:'High Resale Potential'}]

export default function DashboardPage(){return(<div style={{display:'flex',flexDirection:'column',gap:22,paddingBottom:40}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:20,borderBottom:'1px solid #18181b',paddingBottom:20}}><div><div style={{fontSize:11,letterSpacing:'.12em',textTransform:'uppercase',color:'#71717a',marginBottom:10}}>Recruitment Intelligence System</div><h1 style={{fontSize:48,lineHeight:1,fontWeight:900,letterSpacing:'-.06em',margin:'0 0 12px',color:'#fafafa'}}>Scouting Operations Center</h1><p style={{color:'#71717a',maxWidth:760,lineHeight:1.7,fontSize:15}}>Live recruitment intelligence platform combining StatsBomb data, role archetypes, percentile modeling and scouting workflows.</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(140px,1fr))',gap:10,minWidth:320}}><Metric label='Tracked Players' value='12,659'/><Metric label='Active Watchlists' value='24'/><Metric label='Market Alerts' value='37'/><Metric label='Leagues Indexed' value='24'/></div></div><div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr',gap:18}}><section style={panel}><SectionTitle title='Recruitment Feed' subtitle='Live scouting intelligence'/><div style={{display:'grid',gap:12}}>{risers.map(player=><div key={player.name} style={feed}><div><strong style={{fontSize:14}}>{player.name}</strong><div style={{fontSize:12,color:'#71717a'}}>{player.club}</div></div><div style={{color:'#4ade80',fontWeight:700,fontSize:12}}>{player.trend}</div></div>)}</div></section><section style={panel}><SectionTitle title='Market Opportunities' subtitle='Monchi radar signals'/><div style={{display:'grid',gap:10}}>{opportunities.map(player=><div key={player.name} style={feed}><div><strong style={{fontSize:13}}>{player.name}</strong><div style={{fontSize:11,color:'#71717a'}}>{player.tag}</div></div><div style={pill}>Priority</div></div>)}</div></section></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:18}}><section style={panel}><SectionTitle title='Positional Needs' subtitle='Squad planning'/><div style={{display:'grid',gap:10}}><Need role='Left Back' severity='High'/><Need role='Progressive CB' severity='Medium'/><Need role='U23 Winger' severity='High'/></div></section><section style={panel}><SectionTitle title='Watchlist Activity' subtitle='Recruitment workflow'/><div style={{display:'grid',gap:10}}><Activity text='João Pedro promoted to priority target'/><Activity text='Scouting report completed for Cherki'/><Activity text='Vermeeren added to midfield succession list'/></div></section><section style={panel}><SectionTitle title='Recruitment Pipeline' subtitle='Operational overview'/><div style={{display:'flex',flexDirection:'column',gap:12}}><Pipeline stage='Scouted' value='84'/><Pipeline stage='Shortlisted' value='26'/><Pipeline stage='Priority' value='11'/></div></section></div></div>)}

function SectionTitle({title,subtitle}:{title:string;subtitle:string}){return<div style={{marginBottom:18}}><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'.12em',color:'#52525b',marginBottom:6}}>{subtitle}</div><h2 style={{margin:0,fontSize:18,fontWeight:800,color:'#fafafa'}}>{title}</h2></div>}
function Metric({label,value}:{label:string;value:string}){return<div style={{background:'#111114',border:'1px solid #18181b',padding:14,borderRadius:16}}><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'.08em',color:'#71717a',marginBottom:8}}>{label}</div><div style={{fontSize:24,fontWeight:900,color:'#fafafa'}}>{value}</div></div>}
function Need({role,severity}:{role:string;severity:string}){return<div style={feed}><div style={{fontWeight:700}}>{role}</div><div style={severity==='High'?pillDanger:pill}>{severity}</div></div>}
function Activity({text}:{text:string}){return<div style={{padding:'12px 0',borderBottom:'1px solid #18181b',fontSize:13,color:'#d4d4d8'}}>{text}</div>}
function Pipeline({stage,value}:{stage:string;value:string}){return<div><div style={{display:'flex',justifyContent:'space-between',marginBottom:6,fontSize:12}}><span style={{color:'#a1a1aa'}}>{stage}</span><strong>{value}</strong></div><div style={{height:8,borderRadius:999,background:'#18181b'}}><div style={{width:`${Math.min(Number(value),100)}%`,height:'100%',background:'#22c55e',borderRadius:999}}></div></div></div>}
const panel={background:'#0f0f12',border:'1px solid #18181b',borderRadius:24,padding:20,boxShadow:'0 20px 60px rgba(0,0,0,.45)'}
const feed={display:'flex',justifyContent:'space-between',alignItems:'center',padding:'14px 0',borderBottom:'1px solid #18181b'}
const pill={background:'rgba(34,197,94,.12)',color:'#4ade80',padding:'6px 10px',borderRadius:999,fontSize:11,fontWeight:800,textTransform:'uppercase',letterSpacing:'.06em'}
const pillDanger={background:'rgba(239,68,68,.12)',color:'#f87171',padding:'6px 10px',borderRadius:999,fontSize:11,fontWeight:800,textTransform:'uppercase',letterSpacing:'.06em'}
